/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_stanwind_CurlWrapper */

#ifndef _Included_com_stanwind_CurlWrapper
#define _Included_com_stanwind_CurlWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_stanwind_CurlWrapper
 * Method:    curlVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_stanwind_CurlWrapper_curlVersion
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
